### PR TITLE
Update language selection renderer

### PR DESCRIPTION
**Pull request by makiam**
Update renderer to properly render list items when hovered with mouse

### CODE REVIEW

**Comment by Sailsman63** [comment]
What is the intent here? Just a cleaner implementation, or something more?

**Comment by makiam** [comment]
Before this fix
изображение
And after
изображение

**Comment by Sailsman63** [comment]
I can't duplicate that issue so far. What java? I'm assuming you're running windows...

**Comment by peteihis** [comment]
>I can't duplicate that issue so

I pointed that blanking text out already before. Windows & Java 11.

**Comment by makiam** [comment]
See this with Windows 10 and Java 11 and Java 18
Not reproduced on Linux Mint

**Comment by Sailsman63** [comment]
@peteihis I must have missed that while sorting through the comments in that post. Can you confirm that this change fixes it on your machine? I still can't duplicate the issue on linux, but this change does still run normally (As well as looking neater!)

**Comment by makiam** [comment]
This change fixes rendering issue on my Windows desktop as I shows on screenshots above. And yes this rendering glitch is windows specific and not reproduced on Linux

**Comment by peteihis** [comment]
> Can you confirm that this change fixes it on your machine?

Confirmed.

**Pull request merged**
