### PR TITLE
Cleanup code.

### PR DESCRIPTION
**Pull request by makiam**

### CODE REVIEW

**Comment by makiam** [comment]
Seems I do something wrong. (I'm new with git cvs)
I try to rebase to this revision:
commit 2a43e1d9de75e25a6fe57d1d795a1073e4eb0922
Reflog: HEAD@{11} (makiam <maxtemplaar@gmail.com>)
Reflog message: clone: from https://github.com/makiam/ArtOfIllusion.git
Author: Sailsman63 <lukejsails@gmail.com>

E:\Work Files\GitHub\ArtOfIllusion>git rebase HEAD@{11} -Xignore-all-space
Current branch master is up to date.

E:\Work Files\GitHub\ArtOfIllusion>git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

**Comment by Sailsman63** [comment]
Well, I'm newer to git as well, and apparently i gave you the wrong command. Let me work on that a bit.

**Comment by Sailsman63** [comment]
Alright, got it. I'm pretty sure that you are using Windows and a standard windows text editor (notepad?). Windows is a little... quirky... in how it does certain things. It likes to save an extra character at the end of every line. Other OSs don't like this. Thankfully, git knows how to handle this situation. You just need to tell it that you want it to.

if you run `git config --global core.autocrlf true` git will know to clean up windows saved files into cross-platform compatible form. __This is Global__ if you have *any* other git repositories, it will affect how files are saved in them as well. If you don't want this to happen, we will need to look into a local version of that setting.

Then, to clear the existing line endings from your commit tree, `git rebase <master commit> -f --ignore-whitespace`

I've done it with a local copy, and it works. I just want you to get the credit, so it's better pushed from your end.

BTW, Have you interacted with the AOI community in any other venues?

**Comment by makiam** [comment]
Seems that has no effect. Please close this request as invalid. I setup my tools (Netbeans) to work better and apply this changes from scratch.

PS. I never interact wit AOI community before.

**Comment by Sailsman63** [comment]
Please don't go back to do all that work by hand. I'll push up to a branch, and we can work from there. I'm trying to figure out why this did not work as anticipated.

Just a thought for the future: to give yourself a safe fallback, you may wish to create a new branch each time you start a project like this one, rather than commit directly to your master branch.

**Comment by Sailsman63** [comment]
Looking closer, it looks like you did your rebase in a branch, and then merged it back on to the master that already had the windows endings. This is another reason to branch before making changes. Don't worry, it gets easier! We do appreciate the time and effort you have spent so far.

I've pushed a clean version to the branch makiam-refactoring here in the main repository. Can you tell me if it appears to have the changes as you intended them?

**Comment by makiam** [comment]
Looks ok.
Thank You.

**Comment by peastman** [comment]
Anywhere you create a Logger object, the spacing is inconsistent with the surrounding code.  Things like this appear in lots of files:

```Java
public class ApplicationPreferences
{
    private static final Logger logger = Logger.getLogger(ApplicationPreferences.class.getName());
    
  private Properties properties;
  private int defaultDisplayMode, undoLevels;
  private double interactiveTol;
```

**Comment by Sailsman63** [comment]
@peastman in going through this code, I've come to the conclusion that some, at least, was created by an IDE auto-filling its suggested changes. Due to the windows Line Ending compatibility thing, and the fact that the history of this branch is a bit of a mess due to my unclear suggestions, I was intending to close this PR. 

@makiam I've cleaned up the line ending issue, and split these changes out into PR #5, #6, #7, #8. as you actually have several conceptual changes here.

**Comment by Sailsman63** [comment]
@makiam I'm closing this PR. We're definitely looking at your contributions, but some of it needs more thought. Please check in on #5, #6, #7, and #8. In the future, you won't need to worry about the line ending thing. I've added some settings to the repository that will take care of it automatically. Please don't hesitate to continue to work with AOI - We appreciate your efforts.

**Pull request closed without merging**
