### PR TITLE
unify styling of comment types

### PR DESCRIPTION
**Pull request by Sailsman63**
Make sure that documentation-style comments are styled like other comments. I think these just got missed originally.

### CODE REVIEW

**Comment by peteihis** [comment]
That should do it, though I probably would have called the 'newStyle' something bit more unique. :)

**Comment by Sailsman63** [comment]
Got the paren-matching to highlight both ends of a pair, and toned down the outline. Hopefully a little easier on the eyes.

> probably would have called the 'newStyle' something bit more unique. :)

What I *should* do is remove all of the code altogether and use an XML theme, as supported by the library. Puts all of the details in one place, instead of duplications.

**Comment by peteihis** [comment]
> Hopefully a little easier on the eyes.

Definitely! -- Quite nice actually. 

Now, being as subtle as it is, it makes me notice, what I have been thinking all along that the colors in general could take serious taming down but that's a different project _(--> candidade for the xml-theme, I guess)_.

**Comment by Sailsman63** [comment]
This was still itching at me a bit, so I went ahead and transitioned to the XML theme. Tweaking the colors should be simple from here, if you have thoughts.

I do want to de-duplicate the loading code, but we need a better way to communicate where configuration resources can be found.

**Comment by makiam** [comment]
Missed now tabSize setup for all editors and also missed codeFolding enablement for KeyStroke script editor

**Comment by Sailsman63** [comment]
Yes, I did. Fixed. Thanks!

**Comment by Sailsman63** [comment]
And... I couldn't just leave it alone. I ended up extracting the common functionality out into a separate widget. Probably more to be done here, built on top of it.

I wasn't able to do quite what I anticipated. This widget is a little odd by buoy standards - the RSTA components are in a tight little stack that doesn't compose the way I'd normally approach things. I particular, I don't think that it's possible to remove the awt/swing style `KeyListener` from `artofillusion.script.ExecuteScriptWindow` without re-implementing it somewhere else.

**Comment by Sailsman63** [comment]
And one last tweak. I got the RSTA properly wrapped in Buoy components, which allows to move to the buoy event mechanism. As a bonus, this fixes the layout bug #283 - I suspect that the old way just wasn't triggering a re-layout correctly, while the more specialized buoy `BTextArea` has this already properly daisy-chained in.

**Comment by Sailsman63** [comment]
Final call for feedback on the code changes!

- Suggestions for alternative color schemes should probably be talked out separately.
- Discussions about other UI/UX concerns wrt the script editors and menus should also have their own discussions

**Pull request merged**
