### PR TITLE
Made artofillusion.procedural package accessible for scripting engine

### PR DESCRIPTION
**Pull request by makiam**
Made artofillusion.procedural package accessible for scripting engine

### CODE REVIEW

**Comment by peteihis** [comment]
I have ben wondering why the animation package is not visible to scripting? There probably is a reason, but I'd like hear, what the thinking behind it is?>

**Comment by Sailsman63** [comment]
Essentially, `artofillusion.procedure` contains _only_ procedural modules. These modules are intended to be manipulated through the graphical interface, not code. Trying to access them in a script makes no sense. and could lead to some very strange behavior.

If you need to create a texture in a script, you are better off writing the entire texture in code.

**Comment by makiam** [comment]
Classes from artofillusion.procedure are still accessible with FQN. Adding this package to imports gives only a bit comfortable way to access classes.

**Comment by Sailsman63** [comment]
That's true, but part of the point is that the extra friction should make you stop and ask if what you are doing makes sense.

**Pull request closed without merging**
