### PR TITLE
Navigation fixes

### PR DESCRIPTION
**Pull request by peteihis**
A PR for fixes to the view manipulation.

### CODE REVIEW

**Comment by peteihis** [comment]
Added a propper undo to the scroll wheel moves of the SceneCamera. Should have done the tab-character removal first, but better late than never I guess?

**Comment by peteihis** [comment]
Scrollwheel travel checks if orientation changes during scroll. If the orientation is set to "Other" it does not check if the orientation would match a preset. The check could be added, but a (re)match would be rather an unlikely case.

**Comment by peteihis** [comment]
ViewAnimation and a navigation change will now update ObjectProperties if an affected object (a camera) is selected.

**Comment by peteihis** [comment]
Ooh rats! .. I just discovered a bug in this branch... I have no idea why, but the timemarker on the score does not move during preview. I'll be back...

**Comment by peteihis** [comment]
And found it. Fix added to the previous push.

**Comment by Sailsman63** [comment]
Thanks for taking a look. I'll have to do some testing, etc. when I get a chance.

As a note, though, please __do not__ do tab removal when working on a file. This adds a lot of noise to the pr/commit history. Instead, make a note of files that seem to have a lot of tabs. In the future, we should go through and fix tab/whitespace issue _in a single, separate PR_.

**Comment by peteihis** [comment]
> do not do tab removal

OK...

>I'll have to do some testing, etc. when I get a chance.

There are still things missing from this PR. It seems that I'll have to study a few things a bit deeper. Trying to fix some rather minir things seem to produce side effects, that I was not anticipating and I need to map out what is happening.

**Comment by peteihis** [comment]
This fixes the behavior of the navigation mode selection in the case that an animation track tilts the camera.

Some tab replacement happend, but it could not really be helped this time.

**Comment by Sailsman63** [comment]
Okay, Finally got a chance to clean up the whitespace issues. Take a look at #76. See how much easier it is to see the _important_ changes?

**Comment by peteihis** [comment]
Sorry for the yet another long silence -- Hoping that I can get back on track soonish...

So,  I'll rebase my branch on yours now?

**Comment by Sailsman63** [comment]
>Sorry for the yet another long silence

That's okay. I've been mostly distracted by other things as well.

>So, I'll rebase my branch on yours now?

No. That won't do what  you think. I've mostly kept the branches open just in case @peastman noticed anything else. I'll review my branch again later today, (It has _all_ of your changes, with you credited as the author...) and if everything looks good, I'll merge it into Master.

**Comment by peteihis** [comment]
> I'll merge it into Master.

That's, would have been my next suggestion :D ... I have a few more things I was testing, but what is already is should work as it is.

There are still some things "a little bit" off with the handling of light cameras, that I'd like the get under control but, when I was testing it, solving one issue seemed to arise others ... I might leave that for later. _(I think I'll end up making a change to the priciple the parallel/perspective modes are handled internally. It should make things easier afterwards, but there seems to a lot of places that would be affected. -- The fast forward way would be to go `if (...)`, but that'd lead to special cases over special cases, which is not a small project either and adds unnecessary complexity --> Probably has to wait past 3.1)_

Other than that I think, I'll just try to cut out some features, that have been found confusing and focus on getting the 3.1 out. -- Then plan a modernization round with the layers and the `mouseMoved`-functions as those two are pretty closely related.

**Comment by Sailsman63** [comment]
>when I was testing it, solving one issue seemed to arise others

Sounds like some of the code does things that you don't quite understand... or interacts with other code in complex ways. "You keep changing that code. I do not think it does what you think it does"

>I'll just try to cut out some features, that have been found confusing and focus on getting the 3.1 out.

We need to decide _what_ we need to do. Mostly to make the control modes easier to discover. Please discuss that over on issue #64.

**Pull request closed without merging**
