### PR TITLE
ObjectSet save fixed

### PR DESCRIPTION
**Pull request by peteihis**
As per subject.

### CODE REVIEW

**Comment by Sailsman63** [comment]
Thanks for the quick fix!

Question: did you try it *without* the setter? I Wasn't *Certain* that we would need it, just seemed like it would be possible, depending on the underlying code...

**Comment by peteihis** [comment]
> Question: did you try it without the setter?

I did. The ObjetSets came back empty, only with their names.

**Comment by peteihis** [comment]
I remember now that the spec does say, that it needs a no-args constructor and dedicated set and get method pairs for the data.

**Comment by Sailsman63** [comment]
Thanks for checking. That actually makes sense - it generates a `new ObjectSet()` and then uses the setters to actually restore the data.

**Pull request merged**
