### PR TITLE
View menu to Scene view

### PR DESCRIPTION
**Pull request by peteihis**
Hi!

Added view menu to LayoutWindow. 
The DisplayModeIcons plugin works after this change. 

Not sure if I used GitHub as I was supposed to. If not, I'd be happy to try another time. :)

-P-

### CODE REVIEW

**Comment by Sailsman63** [comment]
Hey there! Welcome to the github side of things, and congratulations on your first pull request. This looks like a great idea, and the implementation is nice and clean. Unless @peastman has concerns about where this idea is heading, I'll merge it fairly soon.

**Comment by Sailsman63** [comment]
@peteihis The way this pull request is structured is 'correct.' I'll be able to merge it with no problem at all for the project, and since it'll be the next thing merged, it will not cause you any problems either.

However. You may in the future find yourself in difficulty if you work and generate pull requests from your 'master' branch. You generally want to keep your 'master' clean, and pull all updates from the main repository into it. This gives you a safe place to start from for multiple projects.

For each feature that you hope to create, you will probably want to work in a separate branch. For example, some of the view manipulation stuff you have been talking about might be implemented in a branch named 'better Modeling manipulation' or similar.

If a feature takes a long time and overlaps other contributions in time, it will be a fairly simple thing to pull the other contributions down into your 'master' and then update your feature branch on top of them. I'll be glad to help you through that part when it comes up, but doing your work in a branch makes it a lot easier.

Its not uncommon to end up with multiple branches if you are working on multiple projects. I've currently got three active ones, and will probably have more in the future, depending on what projects I'm working on.

Questions or clarification? Let me know. I'd be glad to help.

**Comment by peteihis** [comment]
That's what I thought....

Somehow I first managed to create a couple of empty branches and the found
a way to delete them and then the changes ended up directly in the master
and I did not find a way to take it back an try again.

So I suppose I'd have to be in a local branch (which I did have, but was in
the master) when I do the push and then that branch appears in the hub?

-P-




2016-10-17 20:38 GMT+03:00 Sailsman63 <notifications@github.com>:

**Comment by Sailsman63** [comment]
@peteihis Yes, you work in a local branch. If you are doing the push from command line, it will look like:

    git push <name of your remote - usually origin> <name of local branch> <name of branch on remote>

If you need to make changes in a branch you have already pushed, just repeat the command. The remote branch will update. If you have an open PR, it will update as well.

**Comment by peteihis** [comment]
That looks like a certainly secure way of getting things where they are
supposed to go.

What would happen if I just:

git checkout mybranch
git push

So locally in the local branch and then just say 'push' without any
arguments? I think I should have another look at the book...

-P-


2016-10-18 14:17 GMT+03:00 Sailsman63 <notifications@github.com>:

**Comment by Sailsman63** [comment]
@peteihis For that to work, you need to set up the local branch to be *tracking* a remote branch. You usually do this for long-running branches that you will use over and over again. I have two:
- Upstream, set to track the project master branch
- Master tracks the master branch on my github fork

You may not need both, it makes it easier for me to do slightly more complex things.
For shorter-term feature branches, setting up the tracking is often more effort than it's worth.

**Comment by peteihis** [comment]
> You usually do this for long-running branches

This might be it....

2016-10-19 0:42 GMT+03:00 Sailsman63 <notifications@github.com>:

**Comment by peastman** [comment]
> git checkout mybranch
> git push

That's almost right.  Try this:

```
git checkout -b mybranch
git push origin mybranch
```

If you do that, I think it will do exactly what you want.

And remember, if your local repository ever gets too messed up, just delete the whole thing and recreate it from scratch.  See https://xkcd.com/1597 for details. :)

**Comment by Sailsman63** [comment]
Just for clarity: the '-b' in 'git checkout -b mybranch' is a shortcut that you use to _create_ the branch you are checking out. If you have been moving around your repository, and want to check out an existing branch,  you use 'git checkout mybranch'

**Comment by peteihis** [comment]
I think I got it. :) & Thanks.

**Pull request merged**
