### PR TITLE
Move procedural module background render code to Procedure Editor

### PR DESCRIPTION
**Pull request by makiam**

### CODE REVIEW

**Comment by makiam** [comment]
>> What prompted the change to the second in this case?
There are not clear second case nor first case but combined approach. The module know how to draw itself and it is remains unchanged. But ProcedureEditor controls modules selected/unselected state and know how to draw this state and draw common module background (which is always the same for all modules)

Also I want to try to rework this editor and made rendering colors customizable. This PR is for it.

**Comment by Sailsman63** [comment]
This introduces inconsistency on how the UI is modeled, though. AOI tends toward "Object knows how to represent *itself* visually." (And, indeed, you're still allowing the `IOPort`s to draw themselves, which means you're hopping between architectural models in very closely related code.)

> Also I want to try to rework this editor and made rendering colors customizable. This PR is for it.

Why would that goal require this change?

**Comment by Sailsman63** [comment]
I think you misunderstood me. Please take a step back and explain why this change is needed to meet your overall goal.

**Comment by Sailsman63** [comment]
Without understanding why this change is necessary, I can't properly evaluate or review. Closing for now.

**Pull request closed without merging**
