### PR TITLE
Update module duplicate result type

### PR DESCRIPTION
**Pull request by makiam**
Update procedural module's duplicate() method declaration to be more specific. This reduces dependencies count of deprecated Module class

### CODE REVIEW

**Comment by Sailsman63** [comment]
No. This is a part of the public API. It *Must* return the more general type, which is still `Module.`When we are ready to remove the deprecated code, it will then need to return `ProceduralModule`

**Comment by makiam** [comment]
This fix is not violates Module contract because more specific type returns is still Is-a module.

**Comment by peastman** [comment]
I think this is ok.  Covarient return types have been supported all the way back to Java 5.

**Comment by Sailsman63** [comment]
You know, you may have a point. I've always stayed away from them because it felt wrong, even though it's legal.

I've never seen a compelling use case - do you find that this makes the code easier to read?

**Comment by peastman** [comment]
It can avoid unnecessary type casts, so yes, it makes the code easier to read.  And it's generally safer.  The more specific the return type is, the more information the compiler has for catching errors.

**Comment by Sailsman63** [comment]
> avoid unnecessary type casts

That's true if the calling code cares about what type of module it gets.

I'm having trouble imagining an instance where you would call this method *and know/care what kind of module you get.* To me, the more generic return type is part of the documentation. It says "Hey, this is part of a bigger system. If you're thinking of calling this, you really should be planning on handling *any* type of module."

**Comment by peastman** [comment]
If you're writing generic code to process procedures you probably won't care.  But if you're writing, for example, a plugin that builds procedures programmatically, there's a good chance you'll care about the return type.

Just as a matter of principle, I think it's always good to make signatures as specific as possible.  If you know the return value will always be a particular class, say so.  It will never hurt and will sometimes help.  In fact, I'd vote for making this same change to all `duplicate()` methods (objects, textures, etc.).

**Comment by Sailsman63** [comment]
Okay, I see where you're coming from.

Let's go for it.

**Pull request merged**
