### PR TITLE
Save RenderSetupDialog settings to metadata 

### LINKED ISSUE #230: Saving Render Dialog settings
Just wanted to let you know that I'm working on that. Should not take too long.

- Currently the settings of the selected renderer are saved but settings that belong to the dialog, like the image size, are not. 
- Also , I found that when you open a file and use 'Render Immediately' before doing anything else, on the first time the renderer settings are not read from metadata. The second time they are.

### PR DESCRIPTION
**Pull request by peteihis**
Resolves #230.

Now it checks if settings have changed and if so call `setModified()`. An addition to the`Renderer` interface was needed get the information the renderers but it seems that renderers that have been compiled before the change would still work if they are otherwise compatible.

I came up with a kind of a hidden feature for cases where the user _(well myself at least)_ might like to save already changed settings on Cancel. Let me know what you think.

### CODE REVIEW

**Comment by Sailsman63** [comment]
>seems that renderers that have been compiled before the change would still work if they are otherwise compatible.

No, they actually don't. They'll *load* just fine, but the moment that the dialog tries to check if any settings have been modified, things crash.

**Comment by peteihis** [comment]
I seem to get varying results. I may have an idea, but I'll be back at it on the weekend....

I think a8eef0a should be OK as such though.

**Comment by Sailsman63** [comment]
It should be.

A thought: I don't think that it would be all that difficult to include a `private class foo extends PanelDialog` that added a third button. You'd have:

- Okay (Save settings to file and render)
- Cancel (Dismiss dialog without saving)
- Save Settings for later (Save settings to scene & Probably? dismiss dialog)

This would save a whole bunch of complexity trying to figure out if settings have been changed, etc. and probably prevents any need to extend the Renderer interface.

**Comment by peteihis** [comment]
> This would save a whole bunch of complexity trying to figure out if settings have been changed

Not really. I tried a _trick or two_....

Checking if any of the values are changing (`boolean`) is not much different from checking how many of them are changing (`ìnt`).

And because the `Renderer` interface does not provide any channel to check if values have changed and the renderers are only known as 'Renderer' it is not possible to get anything from the renderer to the core SW around the interface. -- And naturally it is not possible to `import RaytracerRenderer` or the other one into the dialog as they are plugins. ( `( RaytracerRenderer)currentRenderer.modified...` would seem simple but `can not find symbol`).

The two ways to do it are either to send the parent (with the scene included) to the renderer or to ask the renderer about values that are going to change. Somehow the latter seems lighter to me but the as this is not nearly the only place where `modified` is not updated correctly the uniform approach could just be to sent the main `LayoutWindow` everywhere.

OTOH I'm not aware of any plugin renderers that would work with the current version any way....  But I'll test a _third or so_ trick and get back.

The buttons then, if that's the way you'd like to go, to me "Save settings" and "Reset renderer" would make a nice pair to work with. A "Save and exit" would seem a kind of blunt/unnecessary as there already are four different ways to exit the dialog. -- And the reset would make life easier to someone who is new to it... It's pretty easy the get confused if you don't know what everything is about (as I vaguely recall ;) ).

**Comment by Sailsman63** [comment]
>Checking if any of the values are changing (boolean) is not much different from checking how many of them are changing (int).

My point was to avoid checking this at all.

- Render *Always* writes metadata
- Cancel *Never* writes metadata
- Save Settings *Always* writes metadata (and could very well leave the dialog open)
- No "Reset" button. That's what Undo in the main window is for.

**Comment by peteihis** [comment]
Oh, I see.... _(I may not be at my brightest at this our any more...)_ The point with the reset button would be that if you have tinkered with the settings before and already saved them in a file that you just opened, you would have a way to start over.... But coming to think of it, that is probably not very useful to most of us after all.

**Comment by peteihis** [comment]
> (I may not be at my brightest at this our any more...)

As said -- after a badly slept week.... so:

The primary reason to check if values on the renderer panel have changed is to decide if `LayoutWindow.setModified()` should be called. That can not be avoided if we want the state to be correct. -- And I'm not particularly happy about thoise cases where AoI is either ignoring changes or marking the scene modeified just in case....

I came up with a way to handle the check inside `RenderSettingsDialog`. For the renderer configuration it means that the dialog has to `getConfiguartion()` from the renderer and store the map until "OK". (This is not my _third-or-so-option_ , it was yet different.)

I'll push an update in the evening after some more testing.

**Comment by Sailsman63** [comment]
Okay, the current state looks like a good start to me.

We can consider whether we want to add a "Save Settings" later. Anything you'd like to address before I merge this?

**Comment by peteihis** [comment]
Go ahead.

I though about the Save settings thing but the idea started to crawl towards "Manage settings". I think I have mentioned the idea before and I have a rough idea what I'd what to see there but not much more so far.

**Pull request merged**
